---
- name: Atualizar sistema Linux
  hosts: all
  become: yes

  tasks:
    - name: Atualizar lista de pacotes
      package:
        name: "*"
        state: latest
      when: 
        - ansible_pkg_mgr == 'apt'
        - ansible_pkg_mgr == 'dnf'
        - ansible_pkg_mgr == 'yum'